import * as THREE from './three.module.js';
import { GLTFLoader } from './GLTFLoader.js';
import { DRACOLoader } from './DRACOLoader.js';
import { RGBELoader } from './RGBELoader.js';
const $=s=>document.getElementById(s);let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('overlay').innerHTML='<div class="intro"><h1>3D unavailable</h1><p>Please enable hardware acceleration or try another browser.</p></div>';throw e;}
renderer.domElement.className='webgl';renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;$('game').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#98c6d5');scene.fog=new THREE.Fog('#b4d1d7',230,1000);const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,1800);
scene.add(new THREE.HemisphereLight(0xe5f9ff,0x677c47,1.1));const sun=new THREE.DirectionalLight(0xffe0c4,2.4);sun.position.set(100,180,-70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;sun.shadow.camera.far=400;sun.shadow.bias=-.0005;scene.add(sun,sun.target);
const mat=(c,roughness=.7,metalness=0)=>new THREE.MeshStandardMaterial({color:c,roughness,metalness});const asphalt=mat('#343e46'),white=mat('#e6e9d7'),red=mat('#e36343'),grass=mat('#839e58'),sand=mat('#d4c396');
function mesh(g,m,x=0,y=0,z=0,parent=scene){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,m,x,y,z,p){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p);}
const waterGeo=new THREE.PlaneGeometry(3000,3000,90,90);const sea=mesh(waterGeo,mat('#3b9fb0',.24,.4),0,-2.5,0);sea.rotation.x=-Math.PI/2;
const skyGeo=new THREE.SphereGeometry(1400,32,24);const skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,uniforms:{top:{value:new THREE.Color('#5d9fb9')},bottom:{value:new THREE.Color('#f4dfbb')}},vertexShader:'varying vec3 vPos; void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vPos;void main(){float h=normalize(vPos).y;gl_FragColor=vec4(mix(bottom,top,smoothstep(-0.05,0.6,h)),1.0);}'});const skyDome=new THREE.Mesh(skyGeo,skyMat);scene.add(skyDome);
mesh(new THREE.SphereGeometry(32,24,16),new THREE.MeshBasicMaterial({color:'#fff0c5'}),-680,225,-650);
for(let i=0;i<0;i++){let angle=i/26*Math.PI*2;let m=mesh(new THREE.ConeGeometry(90+i%4*30,100+i%5*35,5),mat('#70969b'),Math.cos(angle)*900,15,Math.sin(angle)*900);m.rotation.y=i;}

mesh(new THREE.CylinderGeometry(1,1,6,100),sand,0,-3,0).scale.set(197,1,277);mesh(new THREE.CylinderGeometry(1,1,2,100),grass,0,-.7,0).scale.set(172,1,252);
const TAU=Math.PI*2;function point(t,lane=0){return new THREE.Vector3((150+lane)*Math.cos(t),.12,(230+lane)*Math.sin(t));}function tangent(t){return new THREE.Vector3(-150*Math.sin(t),0,230*Math.cos(t)).normalize();}
function strip(a,b,material,height=.1){let v=[],idx=[];for(let i=0;i<=320;i++){let t=i/320*TAU;for(const l of [a,b]){let p=point(t,l);v.push(p.x,height,p.z);}if(i<320){let j=i*2;idx.push(j,j+1,j+2,j+1,j+3,j+2);}}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();let m=material.clone();m.side=THREE.DoubleSide;mesh(g,m);}
strip(-12,12,asphalt,.35);strip(-12,-11.6,white,.37);strip(11.6,12,white,.37);
for(let i=0;i<160;i++){let t=i/160*TAU;for(let side of [-1,1]){let p=point(t,side*12.7);let curb=box(1.5,.18,7,i%2?white:red,p.x,.36,p.z);curb.rotation.y=Math.atan2(tangent(t).x,tangent(t).z);}}
for(let i=0;i<110;i++){let t=i/110*TAU,p=point(t);let o=box(.15,.015,3.8,white,p.x,.38,p.z);o.rotation.y=Math.atan2(tangent(t).x,tangent(t).z);}
for(let x=0;x<12;x++)for(let z=0;z<3;z++)box(2,.02,1.1,(x+z)%2?asphalt:white,139+x*2,.4,z*1.1);
const dark=mat('#172d33'),wood=mat('#877157'),leaf=mat('#365f48');
for(let i=0;i<0;i++){let t=i/24*TAU,p=point(t,-65-(i%4)*13);let m=mesh(new THREE.IcosahedronGeometry(13+(i%5)*3,0),mat(i%2?'#8caa73':'#6f925e'),p.x,4,p.z);m.scale.y=1.6;}
for(let i=0;i<0;i++){let p=point(2.1+i*.055,30);box(7,5+i%3*2,7,mat(i%2?'#e5dfcc':'#bfcbd0'),p.x,2,p.z);}
// Start gantry and trackside markers are full 3D geometry.
for(const l of [-15,15]){let p=point(0,l);box(.7,12,.7,dark,p.x,6,0);}box(31,2,1,dark,150,11,0);for(let i=0;i<5;i++)box(2,.55,1.1,mat('#dfff61'),142+i*4,11,0);
for(let i=0;i<90;i++){let a=i/90*TAU;let p=point(a,16.5);let d=tangent(a);const rail=box(.16,.4,12,mat('#c6d0cb',.5,.5),p.x,1.3,p.z);rail.rotation.y=Math.atan2(d.x,d.z);box(.16,1.3,.16,dark,p.x,.65,p.z);}
for(let i=0;i<24;i++){let a=i/24*TAU,p=point(a,-17);box(.18,8,.18,dark,p.x,4,p.z);let pole=box(3.2,.14,.14,dark,p.x+1.5,8,p.z);box(1.1,.13,.5,white,p.x+2.8,7.9,p.z);}
const skidMat=new THREE.MeshBasicMaterial({color:'#1b2126',transparent:true,opacity:.55,depthWrite:false});const skids=[];for(let i=0;i<160;i++){let k=mesh(new THREE.PlaneGeometry(.28,1.5),skidMat,0,-10,0);k.rotation.x=-Math.PI/2;skids.push(k);}let skidIndex=0;
const wheelMat=mat('#121820'),glass=mat('#153740',.18,.5),rim=mat('#bcc7cb',.3,.8);
function car(color){let g=new THREE.Group();scene.add(g);const body=mat(color,.22,.7),carbon=mat('#101c24',.4,.4);
function shell(w1,w2,y1,y2,z1,z2,material){let geo=new THREE.BufferGeometry();let vertices=[-w1,y1,z1,w1,y1,z1,-w2,y2,z2,w2,y2,z2,-w1,.62,z1,w1,.62,z1,-w2,.62,z2,w2,.62,z2];geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setIndex([0,2,1,1,2,3,0,4,2,2,4,6,1,3,5,3,7,5,2,6,3,3,6,7,0,1,4,1,5,4]);for(let i=0;i<geo.index.count;i+=3){let a=geo.index.array[i];geo.index.array[i]=geo.index.array[i+2];geo.index.array[i+2]=a;}geo.computeVertexNormals();let m=mesh(geo,material,0,0,0,g);m.castShadow=true;return m;}
shell(1.16,1.04,.92,1.16,2.4,.5,body);shell(1.04,1.14,1.16,1.08,.5,-2.3,body);shell(.91,.76,1.14,1.75,1,-.05,glass);shell(.76,.95,1.75,1.13,-.65,-1.5,glass);box(1.56,.09,.7,body,0,1.78,-.37,g);box(.08,.07,1.15,body,-.79,1.47,.5,g).rotation.x=.53;box(.08,.07,1.15,body,.79,1.47,.5,g).rotation.x=.53;
box(2.35,.18,4.8,carbon,0,.58,0,g);box(2.4,.08,.5,carbon,0,.58,2.35,g);box(2.42,.09,.55,carbon,0,1.42,-2.05,g);for(let x of [-.8,.8]){box(.08,.4,.1,carbon,x,1.23,-2.06,g);box(.62,.09,.1,new THREE.MeshStandardMaterial({color:'#eeffff',emissive:'#b8eeff',emissiveIntensity:2}),x,.94,2.39,g);box(.7,.075,.09,new THREE.MeshStandardMaterial({color:'#ff3824',emissive:'#ff1600',emissiveIntensity:1.5}),x,1.03,-2.32,g);box(.28,.16,.32,body,x*1.45,1.3,.3,g);}box(1.1,.2,.1,carbon,0,.76,2.42,g);for(let x of [-.28,.28])box(.12,.025,1.6,carbon,x,1.06,1.55,g).rotation.x=.13;
let wheels=[];for(let x of [-1.14,1.14])for(let z of [-1.48,1.48]){let pivot=new THREE.Group();pivot.position.set(x,.54,z);g.add(pivot);let w=mesh(new THREE.CylinderGeometry(.5,.5,.36,24),wheelMat,0,0,0,pivot);w.rotation.z=Math.PI/2;w.castShadow=true;let r=mesh(new THREE.CylinderGeometry(.33,.33,.38,10),rim,0,0,0,pivot);r.rotation.z=Math.PI/2;for(let j=0;j<5;j++){let spoke=box(.4,.04,.48,carbon,0,0,0,pivot);spoke.rotation.x=j/5*Math.PI;}wheels.push(pivot);}
const flames=[];for(let x of [-.72,.72]){const exhaust=mesh(new THREE.CylinderGeometry(.12,.12,.2,12),rim,x,.7,-2.43,g);exhaust.rotation.x=Math.PI/2;let f=mesh(new THREE.ConeGeometry(.16,.9,12),new THREE.MeshBasicMaterial({color:'#88eeff',transparent:true,opacity:.9}),x,.7,-2.9,g);f.rotation.x=-Math.PI/2;f.visible=false;flames.push(f);}g.userData={wheels,flames};return g;}

const player=car('#f2d643');let rivals=[{car:car('#e75c43'),t:.024,lane:-5,v:40},{car:car('#d8e5e1'),t:.046,lane:4,v:42},{car:car('#427dbb'),t:.069,lane:-1,v:44}];
let t=0,lane=4,speed=0,nitro=100,elapsed=0,state='ready',count=0,keys={},steer=0,hitCooldown=0,drifting=false,lateralSpeed=0,cameraMode=0,muted=false,boostActive=false;let audioCtx,osc,engineGain;function initAudio(){if(audioCtx)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();osc=audioCtx.createOscillator();osc.type='sawtooth';let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=400;engineGain=audioCtx.createGain();engineGain.gain.value=0;osc.connect(filter);filter.connect(engineGain);engineGain.connect(audioCtx.destination);osc.start();}catch{}}const total=TAU*3;let assetsReady=false;let crashAt=0;function place(g,t,l){g.position.copy(point(t,l));g.position.y=.4;let d=tangent(t);g.rotation.y=Math.atan2(d.x,d.z);}place(player,t,lane);rivals.forEach(r=>place(r.car,r.t,r.lane));
function reset(){if(!assetsReady)return;player.visible=true;crashAt=0;initAudio();audioCtx?.resume();lateralSpeed=0;t=0;lane=4;speed=0;nitro=100;elapsed=0;count=3.2;hitCooldown=0;rivals.forEach((r,i)=>{r.t=.024+i*.022;});state='countdown';$('overlay').style.display='none';$('pause').textContent='Ⅱ';keys={};}
function pause(){if(state==='racing'){state='paused';keys={};$('notice').textContent='PAUSED';$('pause').textContent='▶';}else if(state==='paused'){state='racing';$('notice').textContent='';$('pause').textContent='Ⅱ';}}
$('start').onclick=reset;$('restart').onclick=reset;$('sound').onclick=()=>{initAudio();muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';};$('camera').onclick=()=>{cameraMode=(cameraMode+1)%3;$('camera').textContent='CAM 0'+(cameraMode+1);};$('pause').onclick=pause;addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(k==='p'&&!e.repeat)pause();if(k==='c'&&!e.repeat)$('camera').click();if(k==='r'&&!e.repeat)reset();if(k==='enter'&&(state==='ready'||state==='finished'||state==='crashed'))reset();});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>{keys={};if(state==='racing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='racing')pause();});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;});
const map=$('map').getContext('2d');function drawMap(){map.clearRect(0,0,200,150);map.lineWidth=8;map.strokeStyle='#ffffff3a';map.beginPath();map.ellipse(100,75,49,58,0,0,TAU);map.stroke();for(const r of [...rivals,{t,player:true}]){map.fillStyle=r.player?'#dfff61':'#ffffff';map.beginPath();map.arc(100+49*Math.cos(r.t),75+58*Math.sin(r.t),r.player?4:3,0,TAU);map.fill();}}
function timeString(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${(s%60).toFixed(2).padStart(5,'0')}`;}
function finish(){state='finished';const rank=1+rivals.filter(r=>r.t>t).length;$('overlay').style.display='flex';$('overlay').querySelector('.eyebrow').textContent='RACE COMPLETE';$('overlay').querySelector('h1').innerHTML=rank===1?'FIRST ACROSS.<br><em>WELL DRIVEN.</em>':`P${rank} FINISH.<br><em>GO AGAIN?</em>`;$('overlay').querySelector('p').textContent=`3 laps completed in ${timeString(elapsed)}.`;$('start').innerHTML='RACE AGAIN <span>↗</span>';}

function crash(){if(state!=='racing')return;state='crashed';speed=0;boostActive=false;keys={};crashAt=performance.now();$('notice').textContent='CRASHED';$('race-message').textContent='ELIMINATED';setTimeout(()=>{if(state!=='crashed')return;player.visible=false;$('notice').textContent='';$('overlay').style.display='flex';$('overlay').querySelector('.eyebrow').textContent='ELIMINATED • COLLISION';$('overlay').querySelector('h1').innerHTML='CRASHED.<br><em>RACE OVER.</em>';$('overlay').querySelector('p').textContent='You hit another car and are out of the race. Start a new race to try again.';$('start').innerHTML='TRY AGAIN <span>↗</span>';},900);}
const draco=new DRACOLoader().setDecoderPath('./');const gltfLoader=new GLTFLoader().setDRACOLoader(draco);
$('start').disabled=true;$('start').textContent='LOADING REALISTIC CARS…';[player,...rivals.map(r=>r.car)].forEach(c=>c.visible=false);
const grassTexture=new THREE.TextureLoader().load('./grass.jpg');grassTexture.wrapS=grassTexture.wrapT=THREE.RepeatWrapping;grassTexture.repeat.set(75,75);grassTexture.colorSpace=THREE.SRGBColorSpace;grass.map=grassTexture;grass.color.set('#a5af89');grass.needsUpdate=true;
Promise.all([gltfLoader.loadAsync('./ferrari.glb'),new RGBELoader().loadAsync('./coast.hdr'),new GLTFLoader().loadAsync('./trees.glb')]).then(([gltf,hdr,trees])=>{const treeTemplate=trees.scene;treeTemplate.updateMatrixWorld(true);const treeParts=[];treeTemplate.traverse(o=>{if(o.isMesh)treeParts.push(o);});const transforms=[];const dummy=new THREE.Object3D();for(let i=0;i<72;i++){const angle=i/72*TAU;const offset=i%3===0?27:-(28+(i%4)*13);const p=point(angle,offset);dummy.position.set(p.x,.25,p.z);dummy.rotation.set(0,i*2.399,0);const size=1.7+(i%5)*.28;dummy.scale.setScalar(size);dummy.updateMatrix();transforms.push(dummy.matrix.clone());}for(const part of treeParts){const material=part.material.clone();if(material.transparent){material.transparent=false;material.alphaTest=.5;material.depthWrite=true;material.side=THREE.DoubleSide;}material.envMapIntensity=.65;const instances=new THREE.InstancedMesh(part.geometry,material,transforms.length);instances.castShadow=true;instances.receiveShadow=true;for(let i=0;i<transforms.length;i++)instances.setMatrixAt(i,transforms[i].clone().multiply(part.matrixWorld));scene.add(instances);}hdr.mapping=THREE.EquirectangularReflectionMapping;scene.environment=hdr;scene.background=hdr;scene.backgroundRotation.y=1.4;scene.environmentIntensity=1.3;skyDome.visible=false;scene.fog=new THREE.FogExp2('#c5c6bd',.0012);
const colors=['#f6bf25','#c82520','#becbd0','#184f82'];const ao=new THREE.TextureLoader().load('./ferrari_ao.png');[player,...rivals.map(r=>r.car)].forEach((root,i)=>{root.children.forEach(c=>c.visible=false);let model=gltf.scene.clone(true);model.rotation.y=Math.PI;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.material=o.material.clone();}});let body=model.getObjectByName('body');if(body)body.material=new THREE.MeshPhysicalMaterial({color:colors[i],metalness:.85,roughness:.25,clearcoat:1,clearcoatRoughness:.08});let glassObj=model.getObjectByName('glass');if(glassObj)glassObj.material=new THREE.MeshPhysicalMaterial({color:'#9cbed0',metalness:.15,roughness:.06,transparent:true,opacity:.75});root.add(model);root.visible=true;root.userData.realWheels=['wheel_fl','wheel_fr','wheel_rl','wheel_rr'].map(n=>model.getObjectByName(n)).filter(Boolean);root.userData.wheels=[];let shade=mesh(new THREE.PlaneGeometry(2.8,5.4),new THREE.MeshBasicMaterial({map:ao,transparent:true,depthWrite:false,blending:THREE.MultiplyBlending,toneMapped:false}),0,.025,0,root);shade.rotation.x=-Math.PI/2;});assetsReady=true;$('start').disabled=false;$('start').innerHTML='START YOUR ENGINE <span>↗</span>';draco.dispose();}).catch(err=>{$('start').textContent='RELOAD TO RETRY';$('overlay').querySelector('p').textContent='The car or environment could not load. Please reload the game.';console.error(err);});

let last=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.04);last=now;
if(state==='countdown'){count-=dt;$('notice').textContent=count>0?Math.ceil(count):'GO';if(count<=0){state='racing';setTimeout(()=>{if(state==='racing')$('notice').textContent='';},700);}}
if(state==='racing'){elapsed+=dt;hitCooldown-=dt;let gas=keys.w||keys.arrowup,brake=keys.s||keys.arrowdown;let boost=keys[' ']&&nitro>1&&gas;boostActive=boost;speed+=((gas?22: -9)-(brake?47:0)-speed*.065)*dt;const max=boost?78:57;speed=Math.max(0,Math.min(max,speed));if(boost){speed=Math.min(78,speed+32*dt);nitro=Math.max(0,nitro-27*dt);}else nitro=Math.min(100,nitro+9*dt);let input=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);steer=THREE.MathUtils.lerp(steer,input,dt*7);drifting=!!keys.shift&&speed>18&&Math.abs(steer)>.2;let targetLateral=steer*(2+speed*(drifting?.21:.12));lateralSpeed=THREE.MathUtils.lerp(lateralSpeed,targetLateral,1-Math.exp(-dt*(drifting?2.2:6)));lane+=lateralSpeed*dt;if(drifting){speed=Math.max(0,speed-3*dt);nitro=Math.min(100,nitro+14*dt);}if(Math.abs(lane)>10.6){speed=Math.max(0,speed-36*dt);lane=THREE.MathUtils.clamp(lane,-16,16);}let derivative=Math.hypot(150*Math.sin(t),230*Math.cos(t));t+=speed*dt/derivative;
for(let r of rivals){let avoidance=Math.abs(r.t-t)<.05&&Math.abs(r.lane-lane)<3?(lane>0?-6:6):Math.sin(elapsed*.35+r.v)*5;r.lane=THREE.MathUtils.lerp(r.lane,avoidance,dt*.8);r.t+=r.v*dt/Math.hypot(150*Math.sin(r.t),230*Math.cos(r.t));place(r.car,r.t,r.lane);if(hitCooldown<=0&&Math.abs(Math.atan2(Math.sin(r.t-t),Math.cos(r.t-t)))*Math.hypot(150*Math.sin(t),230*Math.cos(t))<4.4&&Math.abs(r.lane-lane)<2.05){speed*=.58;lane+=lane>r.lane?1:-1;hitCooldown=1;crash();break;}}if(state==='racing'&&t>=total)finish();}
place(player,t,lane);if(state==='crashed'){player.rotation.y+=(now-crashAt)*.001;player.rotation.z=.12;}for(const root of [player,...rivals.map(r=>r.car)]){root.userData.realWheels?.forEach(w=>{if(state==='racing')w.rotation.x-=(root===player?speed:40)*dt*2.5;});}if(state==='racing'&&drifting){for(let offset of [-.9,.9]){let k=skids[skidIndex++%skids.length],pos=point(t,lane+offset);k.position.set(pos.x,.405,pos.z);k.rotation.z=-player.rotation.y;}}player.rotation.z=-steer*speed*.0007;player.rotation.y-=steer*(drifting?.28:.06);player.userData.wheels.forEach(w=>{if(w.position.z>0)w.rotation.y=-steer*.3;w.children.forEach(c=>c.rotation.x+=speed*dt*1.8);});player.userData.flames.forEach(f=>{f.visible=state==='racing'&&boostActive;f.scale.y=.8+Math.random()*.5;});rivals.forEach(r=>r.car.userData.wheels.forEach(w=>{if(state==='racing')w.children.forEach(c=>c.rotation.x+=r.v*dt*1.8);}));
const direction=tangent(t);let desired=player.position.clone().addScaledVector(direction,-11.5);desired.y+=5;if(cameraMode===1){desired=player.position.clone().addScaledVector(direction,-17);desired.y+=9;}if(cameraMode===2){desired=player.position.clone().addScaledVector(direction,.65);desired.y+=1.75;} if(state==='ready'){desired=player.position.clone().add(new THREE.Vector3(11,6,-13));}camera.position.lerp(desired,1-Math.exp(-5*dt));camera.lookAt(player.position.clone().addScaledVector(direction,11).add(new THREE.Vector3(0,1.2,0)));camera.fov=THREE.MathUtils.lerp(camera.fov,60+speed*.15+(boostActive&&state==='racing'?8:0),dt*3);camera.updateProjectionMatrix();sun.position.copy(player.position).add(new THREE.Vector3(70,160,-70));sun.target.position.copy(player.position);
if(engineGain){engineGain.gain.setTargetAtTime(muted||state==='paused'||state==='ready'||state==='finished'||state==='crashed'||state==='crashed'?0:.035,audioCtx.currentTime,.1);osc.frequency.setTargetAtTime(42+(speed%14)*5+speed*.7,audioCtx.currentTime,.08);}$('gear').textContent=speed<1?'N':Math.min(6,1+Math.floor(speed/13));$('vignette').classList.toggle('boosting',state==='racing'&&boostActive);$('race-message').textContent=state==='crashed'?'ELIMINATED':state==='racing'?(hitCooldown>0?'CONTACT':Math.abs(lane)>10.6?'OFF TRACK':drifting?'DRIFT • NITRO RECHARGING':boostActive?'NITRO ENGAGED':''):'';const wp=waterGeo.attributes.position;for(let i=0;i<wp.count;i++)wp.setZ(i,Math.sin(wp.getX(i)*.035+now*.0006)*.65+Math.cos(wp.getY(i)*.03+now*.0004)*.45);wp.needsUpdate=true;$('speed').textContent=String(Math.round(speed*3.6)).padStart(3,'0');$('boost').style.width=nitro+'%';$('lap').innerHTML=Math.min(3,Math.floor(t/TAU)+1)+'<span>/ 3</span>';$('position').innerHTML=(1+rivals.filter(r=>r.t>t).length)+'<span>/ 4</span>';$('time').textContent=timeString(elapsed);drawMap();renderer.render(scene,camera);}
camera.position.copy(player.position).add(new THREE.Vector3(11,6,-13));requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_race_status',description:'Read current race progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,lap:Math.min(3,Math.floor(t/TAU)+1),speedKmh:Math.round(speed*3.6),time:elapsed})})).catch(()=>{});}catch{}}
